using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WebScraping.Scraper.Flow.Auction
{
    class GetItemMngListJsonData
    {
        public Decimal GoodsNo { get; set; }
        public Boolean GoodsNoSpecified { get; set; }
        public Decimal MasterId { get; set; }
        public Boolean MasterIdSpecified { get; set; }
        public Decimal SiteId { get; set; }
        public Boolean SiteIdSpecified { get; set; }
        public String SellerId { get; set; }
        public String SellerCustNo { get; set; }
        public String SiteGoodsNo { get; set; }
        public Decimal GoodsMasterNo { get; set; }
        public Boolean GoodsMasterNoSpecified { get; set; }
        public Decimal SellType { get; set; }
        public Boolean SellTypeSpecified { get; set; }
        public String CategoryCode { get; set; }
        public String CategoryLName { get; set; }
        public String CategoryMName { get; set; }
        public String CategorySName { get; set; }
        public String CategoryDName { get; set; }
        public String ShopCategoryLName { get; set; }
        public String ShopCategoryMName { get; set; }
        public String ShopCategorySName { get; set; }
        public String SiteCategoryCode { get; set; }
        public Decimal CustCategoryCode { get; set; }
        public Boolean CustCategoryCodeSpecified { get; set; }
        public Decimal CatalogId { get; set; }
        public Boolean CatalogIdSpecified { get; set; }
        public String CatalogName { get; set; }
        public Decimal MakerId { get; set; }
        public Boolean MakerIdSpecified { get; set; }
        public String MakerName { get; set; }
        public Decimal BrandId { get; set; }
        public Boolean BrandIdSpecified { get; set; }
        public String BrandName { get; set; }
        public String UserDefineBrandName { get; set; }
        public String UserDefineMakerName { get; set; }
        public String OptAddSiteGoodsNo { get; set; }
        public String SellManageCode { get; set; }
        public Decimal GoodsType { get; set; }
        public Boolean GoodsTypeSpecified { get; set; }
        public String StatusCode { get; set; }
        public String GoodsName { get; set; }
        public String EngGoodsName { get; set; }
        public String ZnCnGoodsName { get; set; }
        public Decimal StockQty { get; set; }
        public Boolean StockQtySpecified { get; set; }
        public Boolean OptSelUseIs { get; set; }
        public Boolean OptSelUseIsSpecified { get; set; }
        public Boolean OptAddUseIs { get; set; }
        public Boolean OptAddUseIsSpecified { get; set; }
        public Decimal SellPrice { get; set; }
        public Boolean SellPriceSpecified { get; set; }
        public String DispStartDate { get; set; }
        public Boolean DispStartDateSpecified { get; set; }
        public String DispEndDate { get; set; }
        public Boolean DispEndDateSpecified { get; set; }
        public String SiteRegDate { get; set; }
        public Boolean SiteRegDateSpecified { get; set; }
        public String SiteUpdDate { get; set; }
        public Boolean SiteUpdDateSpecified { get; set; }
        public String ListImgUrl { get; set; }
        public Decimal SellCnt { get; set; }
        public Boolean SellCntSpecified { get; set; }
        public Decimal DeliveryType { get; set; }
        public Boolean DeliveryTypeSpecified { get; set; }
        public Decimal DeliveryFeeApplyType { get; set; }
        public Boolean DeliveryFeeApplyTypeSpecified { get; set; }
        public Decimal DeliveryFee { get; set; }
        public Boolean DeliveryFeeSpecified { get; set; }
        public Decimal OptAddDeliveryType { get; set; }
        public Boolean OptAddDeliveryTypeSpecified { get; set; }
        public Boolean MobileOnlyIs { get; set; }
        public Boolean MobileOnlyIsSpecified { get; set; }
        public Decimal IacDcValueType { get; set; }
        public Boolean IacDcValueTypeSpecified { get; set; }
        public Decimal IacDcValue { get; set; }
        public Boolean IacDcValueSpecified { get; set; }
        public Decimal IacPointValueType { get; set; }
        public Boolean IacPointValueTypeSpecified { get; set; }
        public Decimal IacPointValue { get; set; }
        public Boolean IacPointValueSpecified { get; set; }
        public Decimal IacSmileCashbackValue { get; set; }
        public Boolean IacSmileCashbackValueSpecified { get; set; }
        public String IacPremiumEndDate { get; set; }
        public Boolean IacPremiumEndDateSpecified { get; set; }
        public String IacPremiumPlusEndDate { get; set; }
        public Boolean IacPremiumPlusEndDateSpecified { get; set; }
        public String IacAccelerationEndDate { get; set; }
        public Boolean IacAccelerationEndDateSpecified { get; set; }
        public Decimal GmktGmileageRate { get; set; }
        public Boolean GmktGmileageRateSpecified { get; set; }
        public Decimal GstampIssueCnt { get; set; }
        public Boolean GstampIssueCntSpecified { get; set; }
        public Decimal GmktSupplyPrice { get; set; }
        public Boolean GmktSupplyPriceSpecified { get; set; }
        public String GmktFocusEndDate { get; set; }
        public Boolean GmktFocusEndDateSpecified { get; set; }
        public String GmktFocusPlusEndDate { get; set; }
        public Boolean GmktFocusPlusEndDateSpecified { get; set; }
        public String GmktSpricePlusEndDate { get; set; }
        public Boolean GmktSpricePlusEndDateSpecified { get; set; }
        public Decimal GmktSellingStatusCode { get; set; }
        public Boolean GmktSellingStatusCodeSpecified { get; set; }
        public Decimal OverseaAgreeType { get; set; }
        public Boolean OverseaAgreeTypeSpecified { get; set; }
        public String AdiServiceBulkBuy { get; set; }
        public String LastUpd1Date { get; set; }
        public Boolean LastUpd1DateSpecified { get; set; }
        public String LastUpd2Date { get; set; }
        public Boolean LastUpd2DateSpecified { get; set; }
        public String LastUpd3Date { get; set; }
        public Boolean LastUpd3DateSpecified { get; set; }
        public String LastUpd4Date { get; set; }
        public Boolean LastUpd4DateSpecified { get; set; }
        public String LastUpd5Date { get; set; }
        public Boolean LastUpd5DateSpecified { get; set; }
        public String LastUpd6Date { get; set; }
        public Boolean LastUpd6DateSpecified { get; set; }
        public String InsDate { get; set; }
        public Boolean InsDateSpecified { get; set; }
        public String InsOprt { get; set; }
        public String UpdDate { get; set; }
        public Boolean UpdDateSpecified { get; set; }
        public String UpdOprt { get; set; }
        public Decimal TotCnt { get; set; }
        public Boolean TotCntSpecified { get; set; }
        public Decimal PageCnt { get; set; }
        public Boolean PageCntSpecified { get; set; }
        public String GmktDcValueType { get; set; }
        public Decimal GmktDcValue { get; set; }
        public Boolean GmktDcValueSpecified { get; set; }
        public Decimal RowNumber { get; set; }
        public Boolean RowNumberSpecified { get; set; }
        public Decimal NotiItemGroupNo { get; set; }
        public Boolean NotiItemGroupNoSpecified { get; set; }
        public String UserEvaluate { get; set; }
        public Decimal SellerWeight { get; set; }
        public Boolean SellerWeightSpecified { get; set; }
        public String DeliveryWay { get; set; }
        public Decimal MobileThumnailHeight { get; set; }
        public Boolean MobileThumnailHeightSpecified { get; set; }
        public String MobileExposureStatus { get; set; }
        public String MobileInsDate { get; set; }
        public String MobileUpdDate { get; set; }
        public String ShopAttrValue { get; set; }
        public String ShopGoodsUseYn { get; set; }
        public String DupExposeYn { get; set; }
        public Decimal RegStatus { get; set; }
        public Boolean RegStatusSpecified { get; set; }
        public String StatusUpdDate { get; set; }
        public Boolean StatusUpdDateSpecified { get; set; }
        public Boolean IsAllowG9Regist { get; set; }
        public Boolean IsAllowG9RegistSpecified { get; set; }
        public String TransPolicyName { get; set; }
        public String TransType { get; set; }
        public String ReadyDurationDay { get; set; }
        public String TransCloseTime { get; set; }
        public Decimal SdMakerId { get; set; }
        public Boolean SdMakerIdSpecified { get; set; }
        public String SdMakerName { get; set; }
        public Decimal SdBrandId { get; set; }
        public Boolean SdBrandIdSpecified { get; set; }
        public String SdBrandName { get; set; }
        public Decimal SdProductBrandId { get; set; }
        public Boolean SdProductBrandIdSpecified { get; set; }
        public String SdProductBrandName { get; set; }
    }
    class GetItemMngListJson
    {
        public int Total { get; set; }
        public List<GetItemMngListJsonData> Data { get; set; }
        public Boolean Success { get; set; }
        public String Message { get; set; }
    }
}
