using System.Collections.Generic;

namespace WebScraping.Scraper.Flow._11thStreet
{
    class orderingLogisticsNode
    {
        public string RCVR_NM2_VIEW { get; set; }
        public string TMALL_APPLY_DSC_AMT { get; set; }
        public string PRD_NM { get; set; }
        public string ORD_PRD_STAT { get; set; }
        public string ORD_OPT_WON_STL { get; set; }
        public string SNDPLNDDDAYCNT { get; set; }
        public string PRD_NO { get; set; }
        public string MART_STR_NM { get; set; }
        public string PRD_OPT_NM { get; set; }
        public int MART_STR_NO { get; set; }
        public string RCVR_PRTBL_NO_VIEW { get; set; }
        public string ADD_PRD_NO { get; set; }
        public string REAL_LST_DLV_CST { get; set; }
        public string RCVR_NM { get; set; }
        public string ORD_STL_END_DT { get; set; }
        public string MARKET_TYPE { get; set; }
        public string APPMT_DD_DLV_DY { get; set; }
        public string RCVR_TLPHN2 { get; set; }
        public string RCVR_BASE_ADDR { get; set; }
        public string RCVR_TLPHN2_VIEW { get; set; }
        public string PRT_TYP_CD { get; set; }
        public string FR_SEL_PRC { get; set; }
        public string PRD_NM_VIEW { get; set; }
        public string ORD_DLV_REQ_CONT { get; set; }
        public string DLV_CLF { get; set; }
        public string ORD_CN_STEP_CD { get; set; }
        public string INVOICE_FR_PRIME_PRC { get; set; }
        public string SND_PLN_DD { get; set; }
        public string BAR_CD_OUT_CNT { get; set; }
        public string ORD_NO_VIEW { get; set; }
        public string SELLER_ID { get; set; }
        public string RCVR_NM_VIEW { get; set; }
        public string BAR_CD_EXP_YN { get; set; }
        public string PRD_TYP_CD { get; set; }
        public string ORD_PRD_STAT_NM { get; set; }
        public string APPMT_DD_DLV_CD_NM { get; set; }
        public string VISIT_DLV_YN { get; set; }
        public string BAR_CODE_VIEW { get; set; }
        public string GBL_ITG_MEM_NO { get; set; }
        public string CSTM_APL_PRC { get; set; }
        public string RCVR_TLPHN_VIEW { get; set; }
        public string RCVR_BASE_ADDR_VIEW { get; set; }
        public string DECISIONDAYCNT { get; set; }
        public string ABRD_IN_CD { get; set; }
        public string SEL_FEE_AMT { get; set; }
        public string VCENTER_CLM_CNT { get; set; }
        public string ADDR_NM { get; set; }
        public string OPT_NM { get; set; }
        public string RCVR_PRTBL_NO { get; set; }
        public string RCVR_TLPHN { get; set; }
        public string SELLER_PRD_CD { get; set; }
        public string DLV_CLF_CD { get; set; }
        public string SELLER_DSC_PRC { get; set; }
        public string RCVR_BASE_ADDR2_VIEW { get; set; }
        public string RCVR_MAIL_NO_VIEW { get; set; }
        public string BSN_DEAL_CLF { get; set; }
        public string PTNR_ORD_NO { get; set; }
        public string ORD_PRTBL_TEL { get; set; }
        public string MEM_TYP_CD { get; set; }
        public string GBL_LST_DLV_CST { get; set; }
        public string FR_ORDER_AMT { get; set; }
        public string ORD_PRD_SEQ { get; set; }
        public string ADD_PRD_YN { get; set; }
        public string BUY_MEM_NO { get; set; }
        public string DLV_KD_CD_NAME { get; set; }
        public string SEL_PRC { get; set; }
        public string PLCODR_CNF_DT { get; set; }
        public string FEE_TYPE_NM { get; set; }
        public string CARD_PRE_DSC_AMT { get; set; }
        public string FR_PRIME_PRC { get; set; }
        public string RCVR_MAIL_NO { get; set; }
        public string SKT_POINT_DSC_AMT { get; set; }
        public string DLV_CST_STL_TYP_NM { get; set; }
        public string ORDER { get; set; }
        public string BOOKING_FEE { get; set; }
        public string MEM_ID { get; set; }
        public string CUST_GRD_CD { get; set; }
        public string ORDER_AMT { get; set; }
        public int DOLLAR_AMT { get; set; }
        public string FREE_PICKUP_YN { get; set; }
        public string BM_LST_DLV_CST { get; set; }
        public string SEL_FEE_RT { get; set; }
        public string ACTIVATED_NO { get; set; }
        public string ORD_LANG { get; set; }
        public string INVC_UPDATE_DT { get; set; }
        public string RCVR_PRTBL_NO2 { get; set; }
        public string ACTIVATED_YN { get; set; }
        public string REP_TICKET_NO { get; set; }
        public string TICKET_NO_STR { get; set; }
        public string PLAY_PLC_NM { get; set; }
        public string ORD_TYPE_CD { get; set; }
        public string SND_PLN_DD_VIEW { get; set; }
        public string CUST_GRD_NM { get; set; }
        public string PRD_NM_ENG { get; set; }
        public string BONUS_DSC_AMT { get; set; }
        public string RCVR_MAIL_NO2_VIEW { get; set; }
        public string FR_ORD_PRD_STAT_NM { get; set; }
        public string PLU_DSC_AMT { get; set; }
        public string DELVPLACE_SEQ { get; set; }
        public string ACTIVATED_MEMO { get; set; }
        public string RCVR_NM2 { get; set; }
        public string ORD_DT { get; set; }
        public string SND_PLN_DD_RENTAL { get; set; }
        public string PRD_CLF_CD_NM { get; set; }
        public string ORD_QTY { get; set; }
        public string LST_DLV_CST { get; set; }
        public string PART_DLV_YN { get; set; }
        public string DLV_NO { get; set; }
        public string FR_PRD_NM { get; set; }
        public string RCVR_MAIL_NO2 { get; set; }
        public string BAR_CD_OUT_CNT_VIEW { get; set; }
        public string PLAY_DT { get; set; }
        public string TOWN_EXPR_YN { get; set; }
        public string ABRD_IN_CD_NM { get; set; }
        public string ORD_NO { get; set; }
        public string RCVR_BASE_ADDR2 { get; set; }
        public string ORD_NM { get; set; }
        public string SEL_FIXED_FEE { get; set; }
        public string RCVR_PRTBL_NO2_VIEW { get; set; }
        public string SEAT_PRICE_STR { get; set; }
        public string FR_IMP_CHARGE { get; set; }
    }
    class OrderingLogisticsActionJson
    {
        public int totalCount { get; set; }
        public List<orderingLogisticsNode> orderingLogistics { get; set; }
    }
}
