create database blog;
use blog;

CREATE TABLE MST_CATEGORY(
	CATEGORY_CODE CHAR(2) NOT NULL,
	CATEGORY_NAME NVARCHAR(255) NOT NULL,
	URL NVARCHAR(255) NOT NULL,
	ISHOME BOOLEAN DEFAULT FALSE NOT NULL,
	ISDELETED BOOLEAN DEFAULT FALSE NOT NULL,
	SEQUENCE INT NOT NULL,
	
	PRIMARY KEY(CATEGORY_CODE)
);

CREATE TABLE TSN_POST(
	IDX INT NOT NULL AUTO_INCREMENT,
	CATEGORY_CODE CHAR(2) NOT NULL,
	LOCATION VARCHAR(2048) NOT NULL COMMENT 'URL Address',
	CHANGEFREG INT DEFAULT 5 NOT NULL, 
	CREATEDATED DATETIME DEFAULT now() NOT NULL, 
	LAST_UPDATED DATETIME DEFAULT now() NOT NULL,
	PRIORITY INT DEFAULT 5 NOT NULL,
	TITLE NVARCHAR(2048) NOT NULL, 
	FILEPATH VARCHAR(2048) NULL, 
	GUID VARCHAR(255) DEFAULT uuid() NOT NULL, 
	IMAGE LONGBLOB NULL, 
	SUMMARY NVARCHAR(4096) NOT NULL,
	ISDELETED BOOLEAN DEFAULT FALSE NOT NULL,
	
	PRIMARY KEY(IDX),
	FOREIGN KEY(CATEGORY_CODE) REFERENCES MST_CATEGORY(CATEGORY_CODE)
);

INSERT INTO MST_CATEGORY VALUES("01", N'홈', '/', TRUE, FALSE, 1);
INSERT INTO MST_CATEGORY VALUES("02", N'개발일기', '/DialyList.html', FALSE, FALSE, 2);
INSERT INTO MST_CATEGORY VALUES("03", N'개발경험', '/ExperienceList.html', FALSE, FALSE, 3);
INSERT INTO MST_CATEGORY VALUES("04", N'일본생활', '/JapanLifeList.html', FALSE, FALSE, 4);
INSERT INTO MST_CATEGORY VALUES("05", N'한국생활', '/KoreanLifeList.html', FALSE, FALSE, 5);
INSERT INTO MST_CATEGORY VALUES("06", N'코딩노트', '/CodingNodeList.html', FALSE, FALSE, 6);
INSERT INTO MST_CATEGORY VALUES("07", N'즐겨찾기', '/FavoritesList.html', FALSE, FALSE, 7);
