create database blog;
use blog;

CREATE TABLE CATEGORY(
	IDX INT NOT NULL AUTO_INCREMENT,
	CATEGORY_NAME NVARCHAR(255) NOT NULL,
	PARENT INT NULL,
	ICON NVARCHAR(255) NULL,
	
	PRIMARY KEY(IDX),
	FOREIGN KEY(PARENT) REFERENCES CATEGORY(IDX)
);

CREATE TABLE POST(
	IDX INT NOT NULL AUTO_INCREMENT,
	CATEGORY_ID INT NOT NULL,
	LOCATION VARCHAR(2048) NOT NULL,
	CHANGEFREG INT DEFAULT 5 NOT NULL,
	LAST_UPDATED DATETIME DEFAULT now() NOT NULL,
	PRIORITY INT NOT NULL,
	TITLE NVARCHAR(2048) NOT NULL,
	FILEPATH VARCHAR(2048) NULL,
	GUID VARCHAR(255) DEFAULT uuid() NOT NULL,
	IMAGE LONGBLOB NULL,
	
	PRIMARY KEY(IDX),
	FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(IDX)
);

