create database blog;
use blog;

CREATE TABLE MST_CATEGORY(
	IDX INT NOT NULL AUTO_INCREMENT,
	CATEGORY_NAME NVARCHAR(255) NOT NULL,
	
	PRIMARY KEY(IDX),
	FOREIGN KEY(PARENT) REFERENCES CATEGORY(IDX)
);

CREATE TABLE TSN_POST(
	IDX INT NOT NULL AUTO_INCREMENT,
	CATEGORY_ID INT NOT NULL,
	LOCATION VARCHAR(2048) NOT NULL COMMENT 'URL Address', --Be used in sitemap.xml
	CHANGEFREG INT DEFAULT 5 NOT NULL,  -- Be used in sitemap.xml
	CREATEDATED DATETIME DEFAULT not() NOT NULL, -- Be used in post
	LAST_UPDATED DATETIME DEFAULT now() NOT NULL, -- Be used in sitemap.xml
	PRIORITY INT DEFAULT 5 NOT NULL, -- Be used in sitemap.xml
	TITLE NVARCHAR(2048) NOT NULL, -- Be used in post
	FILEPATH VARCHAR(2048) NULL, -- Be used in post
	GUID VARCHAR(255) DEFAULT uuid() NOT NULL, -- Be used in rss
	IMAGE LONGBLOB NULL, -- Be used in list
	SUMMARY NVARCHAR(4096) NOT NULL, -- Be used in list
	IsDeleted BOOLEAN DEFAULT 'FALSE' NOT NULL,
	LANGUAGE CHAR(2) DEFAULT 'kr' NOT NULL,
	
	PRIMARY KEY(IDX),
	FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(IDX)
);

INSERT INTO 
